name: Send POST Request

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to send'
        required: false
        default: 'main'

jobs:
  send-post-request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Make POST Request
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ github.event.inputs.branch }}" ]; then
            BRANCH_NAME="${{ github.event.inputs.branch }}"
          fi
          curl -X POST \
              -H "Content-Type: application/json" \
              -d "{\"message\": \"Workflow triggered\", \"branch\": \"${BRANCH_NAME}\"}" \
              https://evolving-enabled-panther.ngrok-free.app
 
      
      # Optional: Add error handling
      - name: Check for errors
        if: ${{ failure() }}
        run: |
          echo "The POST request failed"
          exit 1
