name: Send POST Request

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  send-post-request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Make POST Request
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               -d '{"message": "Workflow triggered"}' \
               https://31cc-136-25-200-57.ngrok-free.app
        
      # Optional: Add error handling
      - name: Check for errors
        if: ${{ failure() }}
        run: |
          echo "The POST request failed"
          exit 1
